import Head from 'next/head';
// import Image from 'next/image';
import Link from 'next/link';
import Layout from '../components/Layout';
import { getSortedPostsData } from '../lib/posts';
import styles from '../styles/Home.module.scss';

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home({ allPostsData }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <Image src="/images/profile.jpeg" width={300} height={300} alt={"yels"} /> */}
      <div className={layoutStyles.container}>
        <main className={styles.landing}>
          <Layout>
            HELLO!
            <br />
            THIS is WitFLOWER's PORTFOLIO
            {/* {console.log(JSON.stringify(allPostsData))} */}
            {/* <ul>
              {allPostsData.map(({ id, date, title }) => (
                <li key={`${id}`}>
                  {id}. {title}
                  <br />
                  {date}
                </li>
              ))}
            </ul> */}
            <br />
            <Link href={'./top'}>
              <a>GO</a>
            </Link>
          </Layout>
        </main>
      </div>
    </>
  );
}
