import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';
import Link from 'next/link';
import Layout from '@/components/Layout';
import { getSortedPostsData } from '../lib/posts';
import styles from '@/styles/Home.module.scss';
import Footer from '@/components/Footer';
import Navigation from '@/components/Navigation';
import Title from '@/components/Title';

interface Props {}

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

const Home: NextPage<Props> = ({}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <Image src="/images/profile.jpeg" width={300} height={300} alt={"yels"} /> */}
      <Navigation />
      <Layout>
        <div className='container'>
          <div className='inner'>
            <Title element={undefined}>탑 페이지 타이틀</Title>
            <p>안녕하세요 이 페이지는 첫번째 페이지 입니다.</p>
            <p>한글 폰트 테스트</p>
            <p>TEST English Font</p>
          </div>
        </div>
      </Layout>
      <Footer />
    </>
  );
};

export default Home;
