import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React, { useRef } from 'react';
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { getSortedPostsData } from '../lib/posts';
import Layout from '@/components/Layout';
import Navigation from '@/components/Navigation';
// import Parallax from '@/components/Parallax';
import Title from '@/components/Title';
import styles from '@/styles/Home.module.scss';

interface Props {}

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

// todo 1. 팰러렉스 이미지 7장을 내가 포토샵으로 스머징 하듯이 만들어서 이미지만 변경하기. 로고와 같은 비슷한 색상으로
// todo 2. 시작되는 지점에 꽃 3d 이미지 넣기
// todo 3. 스크롤 하는 중간중간에는 다룰 수 있는 기술 혹은 로고들을 회전하듯이 집어넣기. 애플처럼
// 그 외의 상세 내역들은 상세 페이지에 집어넣을건데, 상세페이지는 되도록 깔끔하게 만들기
const Home: NextPage<Props> = ({}) => {
  if (typeof document !== 'undefined') {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const documentRef = useRef(document);

    let scene = new THREE.Scene(); //도화지같은거임
    let renderer = new THREE.WebGLRenderer({
      canvas: documentRef.current.querySelector('#canvas') || undefined,
      antialias: true,
    });
    renderer.outputEncoding = THREE.sRGBEncoding;

    let camera = new THREE.PerspectiveCamera(15, 1);
    camera.position.set(0, 1, 5);
    scene.background = new THREE.Color('white');

    let loader = new GLTFLoader();
    loader.load('/images/scene.gltf', (gltf: any) => {
      scene.add(gltf.scene);

      function animate() {
        requestAnimationFrame(animate);
        gltf.scene.rotation.y += 0.001;
        renderer.render(scene, camera);
      }
      animate();
    });
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <img src="/images/profile.jpeg" width={300} height={300} alt={"yels"} /> */}
      <Navigation />
      <Layout>
        <canvas className='' id='canvas' />
        {/* <div className='container'>
          <div className='inner'>
            <Title element={undefined}>탑 페이지 타이틀</Title>
            <p>안녕하세요 이 페이지는 첫번째 페이지 입니다.</p>
            <p>한글 폰트 테스트</p>
            <p>TEST English Font</p>
          </div>
        </div> */}
        {/* className={styles.lottoBlock} */}
        {/* <Parallax /> */}
        <section className='ef-bg-section'>
          <div className='ef-bg ef-bg1 ef-r spicy'>HELLO!</div>
          <div className='ef-bg ef-bg2 ef-r'>만나서 반가워요</div>
          <div className='ef-bg ef-bg3 ef-l'>
            <h3>This is WitFlower`s SITE</h3>
            <p>
              WitFlower의 포트폴리오 사이트에 오신 것을 환영합니다.
              <br />
              이 페이지에서는 WitFlower의 생각, 스킬, 이력, 일하는 스타일 등을
              보실 수 있어요
              <br />
            </p>
          </div>
          <div className='ef-bg ef-bg3 ef-l'>
            <h5>간략하게 소개소개</h5>
            <p style={{ display: 'none' }}>
              웹 디자이너로 시작해서 프론트 엔드로 경력을 쌓고있는 소시민입니다.
            </p>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default Home;
