import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Layout from "../components/Layout";
import { getSortedPostsData } from "../lib/posts";
import styles from "../styles/Home.module.scss";
import layoutStyles from "../styles/layout.module.scss";

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home({ allPostsData }) {
  return (
    <div className={layoutStyles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Image src="/images/profile.jpeg" width={300} height={300} alt={"yels"} /> */}

      <main className={styles.main}>
        <Layout>
          <h1 className={styles.title}>HELLO WORLD</h1>
          {/* {console.log(JSON.stringify(allPostsData))} */}

          <ul>
            {allPostsData.map(({ id, date, title }) => (
              <li key={`${id}`}>
                {id}. {title}
                <br />
                {date}
              </li>
            ))}
          </ul>
          <div className={styles.grid}>
            <Link href="https://nextjs.org/docs">
              <a className={styles.card}>
                <h2>Documentation &rarr;</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>
            </Link>

            <Link
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <a className={styles.card}>
                <h2>Deploy &rarr;</h2>
                <p>
                  Instantly deploy your Next.js site to a public URL with
                  Vercel.
                </p>
              </a>
            </Link>
          </div>
        </Layout>
      </main>

      <footer className={styles.footer}>
        <Link href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
          <a target="_blank" rel="noopener noreferrer">
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </Link>
      </footer>
    </div>
  );
}
